### ISSUE TITLE
se-2 integrate polygon zkevm main and test net

### ISSUE THREAD

**Issue by OwlWilderness** [scaffold-eth/scaffold-eth-2#310]
se-2 integrate polygon zkevm main and test net

```[tasklist]
### Tasks
- [x] add networks 
- [x] update components wagmi/core 
```

```[tasklist]
### contract deploy and verify
- [x] deploy to test net
- [ ] verify on test net
- [x] deploy to main net
- [x] verify on main net
```
- see pr discussion: may need to downgrade wagmi to 12.8 (currently at 12.10)

**Comment by OwlWilderness** [comment]
### deployed contracts
zkevm testnet [0x248839224e89307ad572c7fbbd4eff30790fe84c](https://testnet-zkevm.polygonscan.com/address/0x248839224e89307ad572c7fbbd4eff30790fe84c)

zkevm mainnet [0x248839224e89307ad572c7fbbd4eff30790fe84c](https://zkevm.polygonscan.com/address/0x248839224e89307ad572c7fbbd4eff30790fe84c)

**Comment by OwlWilderness** [comment]
Hi @technophile-04 
I deployed to mainnet ok and could verify: https://zkevm.polygonscan.com/address/0x248839224e89307ad572c7fbbd4eff30790fe84c#code

however I needed to make make the following updates:
-  update update the yarn verify by removing ethers-. 
-  add custom chains - (maybe there is a component update where this is not needed??) ,   
- verify like the following:
 `yarn verify --network polygonZkEvm 0x248839224E89307AD572C7fBBD4EFF30790FE84c "0x06f0981022DDc612d56250036718cC58cC35eec5"`
- I could not verify on test net (my api key does not work) I am not sure if this is the zkevm api key or alchemy (I did create a second app for test and main)

Please see this branch for modifications.  
- https://github.com/OwlWilderness/se-2/tree/zkevm-verify
- specifically https://github.com/OwlWilderness/se-2/blob/zkevm-verify/packages/hardhat/hardhat.config.ts

added code:
`  etherscan: {
    apiKey: {
      polygonZkEvm: `${etherscanApiKey}`,
      polygonZkEvmTestnet: `${etherscanApiKey}`,
    },
    customChains: [
      {
        network: "polygonZkEvmTestnet",
        chainId: 1442,
        urls: {
          apiURL: "https://api-testnet-zkevm.polygonscan.com/api",
          browserURL: "https://testnet-zkevm.polygonscan.com",
        },
      },
      {
        network: "polygonZkEvm",
        chainId: 1101,
        urls: {
          apiURL: "https://api-zkevm.polygonscan.com/api",
          browserURL: "https://zkevm.polygonscan.com",
        },
      },
    ],
  },`

what i am not sure is if leaving the verify node above will work for other chains (more testing to do)

-demo on mainnet: https://zkevm-smoky.vercel.app/debug

**Comment by damianmarti** [comment]
Thanks @OwlWilderness 

I created an issue to use **hardhat verify** https://github.com/scaffold-eth/scaffold-eth-2/issues/314 because I have the same issue trying to verify a contract that uses external libraries.
