### ISSUE TITLE
Foundry package todo's

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#394]
We have all the basics setup at #353, you run local anvil chain, deploy your contracts, tinker with them on frontend all the commands are similar se-2 `main` branch....checkout out [README.md](https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry#readme) of [`foundry`](https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry#readme) branch for instruction. 

#### some issues / improvements noticed : 

- [x] The `blockexplorer/address/${address}` `code` does not shows anything 
![Screenshot 2023-06-26 at 2 44 41 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/b4fadc0f-a66c-44ff-8fd2-044731fe7277)

- [x] We need to figure out better way for generating `.env` because I think it the current solution will have problem in `Windows` since we are using the forward slash (Maybe having a separate script to generate `.env` ) (We have it already solved it CLI)

- [x] Update the README.md properly (mainly deploying contracts to test / main networks)

- [x] Maybe covert ListAccount.s.sol to .ts / .js file since `ListAccount.s.sol` takes time and throws the output at once.... we can show QR code when using `.js / .ts`.....(We should also remove `ethers` from dependency and use `viem` 🙂)

- [x] Setup typescript, eslint / prettier for code formating of `.js /.ts` files

- [ ] Optional : Check for [forge-deploy](https://github.com/wighawag/forge-deploy) if it have features like `hardhat-deploy` eg. Not deploy a new contract if no changes have happen instead reuse prev one maybe it can also increase devX for deploying and handling deployments

---

Please feel free to tinker around with [`foundry`](https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry) and append issues / suggest any improvements   🙌

**Comment by lucasia** [comment]
Excited to see a foundry version.  Just what I was looking for!  

I noticed a small issue on the foundry branch.  Shall I open an issue for it or add it to this thread?

In: packages/foundry/package.json 

yarn "deploy" tries to run node script/generateTsAbis.**t**s (Typescript) but the script is script/generateTsAbis**.j**s (javascript)

See my code fix: https://github.com/lucasia/se2-foundry/commit/3dcb93d498760e81ac6468d628ba9a7c926ab44c

**Comment by technophile-04** [comment]
Tysm @lucasia for noticing!! Please feel free to make PR 🙌, Also we should update `deploy:verify` too https://github.com/scaffold-eth/scaffold-eth-2/blob/ab06832a5721c91a179f7d578286ba33b641c39c/packages/foundry/package.json#L11

**Comment by lucasia** [comment]
of course, my pleasure!  please see pull request here:
https://github.com/scaffold-eth/scaffold-eth-2/pull/400

kindly review and merge when you have time.  thank you!
-ian

**Comment by jrcarlos2000** [comment]
> Maybe covert ListAccount.s.sol to .ts / .js file since ListAccount.s.sol takes time and throws the output at once.... we can show QR code when using .js / .ts.....(We should also remove ethers from dependency and use viem 🙂)

I think the reason of doing this was because we need to read what are the available networks in `foundry.toml` which we can do through `vm.rpcUrlStructs()`,  while the ts/js version uses hardhat as a dependency.

**Comment by jrcarlos2000** [comment]
>We need to figure out better way for generating `.env` because I think it the current solution will have problem in Windows since we are using the forward slash (Maybe having a separate script to generate `.env` )

i think in windows you only need to run, for it work
```
set >> packages/foundry/.env
```
Probably mentioning it in the `README.md`

**Comment by jrcarlos2000** [comment]
Another TO-DO is : 

- [ ] the `exportDeployments()` function will work for chains that are listed in [stdChains](https://github.com/foundry-rs/forge-std/blob/master/src/StdChains.sol), if you want to deploy to a custom network (i.e. Zetchain / Mantle ) this would break.

**Comment by technophile-04** [comment]
We have tackled this thing in some of recent PR's, Closing this we have a new iteration in issue 470
