### ISSUE TITLE
Update the README when SE-2 Docs website is Live

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/scaffold-eth-2#474]
When we get the initial version of SE-2 Docs website live, we can start working on there for future documentation changes, and leave SE-2 README with the intro+quickstart and a link to the Docs web.

```[tasklist]
### Tasks
- [ ] Remove most of the stuff (maybe just leaving the intro and the quickstart)
- [ ] Add link to [Docs website](http://docs.scaffoldeth.io)
- [x] Explain How to Contribute in [Docs repo](https://github.com/scaffold-eth/se2-docs)
```
